### ISSUE TITLE
Cursor execution not including names and types

### ISSUE THREAD

**Issue by AchilleAsh** [xzkostyan/clickhouse-sqlalchemy#12]
Hi,

I've started to play with your lib and I've noticed one major bug when using the HTTP driver:

When calling the ``` execute()``` method of a _Cursor_ the SQL will not be appended with  ' FORMAT TabSeparatedWithNamesAndTypes' as you could initially expect from the ``` drivers/http/base.py``` file. This causes the result not to include the columns name and therefore the TSV post processing 
(``` drivers/http/connector.py#195 ```)  will go wrong because the first 2 rows are actually data samples.

It seems to me that the following method of _ClickHouseDialect_http_

```python
    def _execute(self, connection, sql):
        sql += ' FORMAT TabSeparatedWithNamesAndTypes'
        return connection.execute(sql)
```

is actually never called (Cursor or not), but I could be wrong.

One quick and easy fix could be to move this to the ``` execute()``` method of _Cursor_.

Thanks,
Timothé

**Comment by xzkostyan** [comment]
Hi,

Yes, there is bug in direct HTTP cursor's `execute()` invocation. Native driver hasn't this disadvantage.

`FORMAT` clause was illegal in some queries as I remember. That's why this hack is located in two places. May be this situation is changed now.

In future I intend to switch default driver from http to native and maybe drop http support.

**Comment by xzkostyan** [comment]
It seems that this was fixed in https://github.com/xzkostyan/clickhouse-sqlalchemy/pull/134.
